import type { Metadata } from "next";
import Link from "next/link";
import { buttonClasses } from "@/components/ui/button";
import {
  BookOpen,
  Gauge,
  Keyboard,
  Library,
  ShieldCheck,
  Sparkles,
} from "lucide-react";

export const metadata: Metadata = {
  title: "About",
  description:
    "What Piano Keys Tab is, how the community works and the rules that keep the library clean.",
};

const VALUES = [
  {
    icon: Sparkles,
    title: "Original content only",
    text: "Every arrangement in the library is community-submitted and reviewed. We never ship copyrighted lyrics or scanned sheet music.",
  },
  {
    icon: ShieldCheck,
    title: "Private by default",
    text: "Passwords are hashed, sessions live in HTTP-only cookies and roles are re-checked on the server for every request.",
  },
  {
    icon: Library,
    title: "Built for practice",
    text: "Transposition, metronome, autoscroll and an interactive keyboard are first-class — not afterthoughts.",
  },
];

const STEPS = [
  { icon: BookOpen, title: "Discover", text: "Search the catalogue by title, artist, tag, key or difficulty." },
  { icon: Keyboard, title: "Practise", text: "Open the practice studio and set the key, tempo and layout that suit you." },
  { icon: Gauge, title: "Progress", text: "Save arrangements, group them into songbooks and rate what helped you." },
];

export default function AboutPage() {
  return (
    <div className="mx-auto max-w-4xl px-4 py-14 sm:px-6">
      <h1 className="text-4xl font-extrabold tracking-tight">About Piano Keys Tab</h1>
      <p className="mt-4 text-lg leading-relaxed text-muted-foreground">
        Piano Keys Tab is a community library of piano arrangements written for people who learn by
        playing. Instead of static PDFs you get searchable tabs with a practice studio built in:
        transpose to a comfortable key, follow a metronome, scroll automatically and watch the notes
        light up on an interactive keyboard.
      </p>

      <section className="mt-12 grid gap-6 sm:grid-cols-3" aria-labelledby="values-heading">
        <h2 id="values-heading" className="sr-only">
          What we value
        </h2>
        {VALUES.map((value) => (
          <div key={value.title} className="rounded-2xl border border-border bg-card p-5">
            <span className="flex h-10 w-10 items-center justify-center rounded-xl bg-primary-soft text-primary">
              <value.icon className="h-5 w-5" aria-hidden="true" />
            </span>
            <h3 className="mt-3 font-semibold">{value.title}</h3>
            <p className="mt-1.5 text-sm text-muted-foreground">{value.text}</p>
          </div>
        ))}
      </section>

      <section className="mt-12" aria-labelledby="how-heading">
        <h2 id="how-heading" className="text-2xl font-bold">
          How it works
        </h2>
        <div className="mt-6 grid gap-6 sm:grid-cols-3">
          {STEPS.map((step, index) => (
            <div key={step.title} className="rounded-2xl border border-border bg-card p-5">
              <div className="flex items-center gap-2">
                <span className="flex h-8 w-8 items-center justify-center rounded-full bg-primary text-xs font-bold text-primary-foreground">
                  {index + 1}
                </span>
                <step.icon className="h-4 w-4 text-primary" aria-hidden="true" />
              </div>
              <h3 className="mt-3 font-semibold">{step.title}</h3>
              <p className="mt-1.5 text-sm text-muted-foreground">{step.text}</p>
            </div>
          ))}
        </div>
      </section>

      <section className="mt-12 rounded-2xl border border-border bg-muted p-6" aria-labelledby="policy-heading">
        <h2 id="policy-heading" className="text-xl font-bold">
          Content policy
        </h2>
        <ul className="mt-3 list-disc space-y-2 pl-5 text-sm text-muted-foreground">
          <li>Arrangements must be your own work or shared with the right to distribute.</li>
          <li>No copyrighted lyrics, scanned sheet music or unattributed transcriptions.</li>
          <li>Covers are generated by the site — we do not host label artwork.</li>
          <li>Comments and arrangements can be reported; moderators act on every report.</li>
        </ul>
        <p className="mt-4 text-sm text-muted-foreground">
          Questions? Read the <Link href="/terms" className="text-primary hover:underline">terms</Link> or{" "}
          <Link href="/contact" className="text-primary hover:underline">get in touch</Link>.
        </p>
      </section>

      <div className="mt-12 flex flex-wrap gap-3">
        <Link href="/songs" className={buttonClasses("primary", "lg")}>
          Browse the library
        </Link>
        <Link href="/register" className={buttonClasses("outline", "lg")}>
          Create an account
        </Link>
      </div>
    </div>
  );
}
